language: bash

services: docker

env:
  - DOCKER_COMPOSE_VERSION=v2.28.1


before_install: 
  - docker -v
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo chmod +x /usr/local/bin/docker-compose

install: 
  - docker compose -f ./docker-compose-build.yaml build --parallel
  - docker tag reverseproxy remichan97/reverseproxy
  - docker tag udagram-api-feed remichan97/udagram-api-feed
  - docker tag udagram-api-user remichan97/udagram-api-user
  - docker tag udagram-frontend remichan97/udagram-frontend
  - docker push remichan97/reverseproxy
  - docker push remichan97/udagram-api-feed
  - docker push remichan97/udagram-api-user
  - docker push remichan97/udagram-frontend