services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feeds
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend